tasks
js-tasks-ru/jsbasic-20220124_kim4001 pull request #6
Opened 2022-02-10 15:57 UTC by KimIgorevich

tasks

2022-02-10 15:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-11 08:16 UTC, koalex requested changes
Нужно решить **`4-1`**

2022-02-15 16:31 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-15 16:32 UTC, KimIgorevich commented
задачи

2022-02-16 03:32 UTC, koalex approved these changes

2022-02-16 03:32 UTC, merged